#
# Executes commands at logout.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
#
quote1="
And as for the critics, tell me I don’t get it.
Everybody can tell you how to do it, they never did it.
  -- Jay-Z
"

quote2="
I'm the greatest
I'm the greatest
I'm the greatest
Pimpin' I'm the greatest
  -- Manny Fresh
"

quote3="
Puff told me like
The key to this joint
The key to staying on top of things
Is treat everything like it's your first project, nomsayin'
Like it's your first day like back when you was an intern
Like, that's how you try to treat things like, just stay hungry
  -- Notorious B.I.G.
"

quote4="
Only fear God
Know the weapons of the weak
The weakness of the heart
And never fall asleep
  -- Lupe Fiasco
"

quote5="
I never sleep, cause sleep is the cousin of death
  -- Nas
"

quote6="
This morning, I woke up
Feeling brand new, I jumped up
Feeling my highs and my lows
In my soul and my goals...
Just to get by, just to get by
  -- Talib Kweli
"

quote7="
I don't bust back because I shoot first
  -- Lil' Wayne
"

quote8="
If I can't do it, Homie, it can't be done
  -- 50 Cent
"

quote9="
Who are the 5 greatest rappers of all time? Dylan, Dylan, Dylan, Dylan, and Dylan.
Because I spit hot fire
  -- Dylan
"

quote10="
Now tell me how you love it
You know you at the top when only heaven's right above it
  -- Lil' Wayne
"

expressions=($quote1 $quote2 $quote3 $quote4 $quote5 $quote6 $quote7 $quote8 $quote9 $quote10)

# Seed random generator
RANDOM=$$$(date +%s)

# Print the message.
cat <<-EOF
${expressions[($RANDOM % ${#expressions[@]}) + 1]}
EOF
