#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

#PYENV Setup
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# Vim Pager for psql!
alias psql='PAGER=vimpsqlpager psql'
alias pgcli='PAGER=vimpgclipager pgcli'

# Unaltered PSQL/PGCLI
alias rpsql='PAGER=less /usr/bin/psql'
alias rpgcli='PAGER=less /usr/local/bin/pgcli'

# from /home/yokley/.bashrc
export EMAIL=kevin.yokley #youremailusername - for database scrubbing
export J2SDKDIR=/usr/lib/jvm/oracle_jdk8
export J2REDIR=/usr/lib/jvm/oracle_jdk8/jre
export PATH=$PATH:/usr/lib/jvm/oracle_jdk8/bin:/usr/lib/jvm/oracle_jdk8/db/bin:/usr/lib/jvm/oracle_jdk8/jre/bin
export JAVA_HOME=/usr/lib/jvm/oracle_jdk8
export DERBY_HOME=/usr/lib/jvm/oracle_jdk8/db

export VT_SHOW_TRACEBACK=true
export VT_DEFAULT_LIST=personal
export VT_PROXY=''
export VT_URL='https://almagest.dyndns.org:7001/vittlify/'

export BROWSER='vivaldi'

export PYENV_VIRTUALENV_DISABLE_PROMPT=1

almagest=(-h almagest.dyndns.org -U yokley)
export PATH=$PATH:~/.cabal/bin
export PATH=$PATH:/usr/local/go/bin

alias google-chrome='google-chrome --disable-gpu-compositing'
# and/or you can set the django settings module with an environment setting
# export DJANGO_SETTINGS_MODULE='dev_settings'

# Custom git command
alias git-scrub='git branch --merged | grep -v master | xargs git branch -d'

# Alias docker commands
alias krill='docker run --rm -it kyokley/krill'
alias ossh='docker run --rm \
                       -it \
                       -p 127.0.0.1:2222-2223:2222-2223 \
                       -p 127.0.0.1:5433:5433 \
                       --privileged \
                       --env HOST=yokley@dev007.us.oracle.com \
                       kyokley/ossh'
alias vt="docker run --rm \
                     -it \
                     -v ~/.ssh:/root/.ssh \
                     --env VT_URL=$VT_URL \
                     --env VT_USERNAME=yokley \
                     --env VT_DEFAULT_LIST=$VT_DEFAULT_LIST \
                     --env VT_PROXY=$VT_PROXY \
                     --net=host \
                     kyokley/vt"
alias color_git_blame="docker run --rm \
                                  -i \
                                  kyokley/color_blame \
                                  color_git_blame"
alias color_svn_blame="docker run --rm \
                                  -i \
                                  kyokley/color_blame \
                                  color_svn_blame"
alias neomutt="docker run -it --rm --name mutt -e TERM \
                          -v $HOME/.mutt/muttrc:/home/user/.neomuttrc:rw \
                          -v $HOME/.msmtprc:/home/user/.msmtprc:ro \
                          -v /etc/localtime:/etc/localtime:ro \
                          -v $HOME/.mutt/header_cache:/home/user/.mutt/header_cache:rw \
                          -v $HOME/.mutt/body_cache:/home/user/.mutt/body_cache \
                          -v $HOME/.mutt/mailcap:/home/user/.mailcap \
                          kyokley/neomutt"

alias cycle_bluetooth="python3 $HOME/workspace/a2dp/a2dp.py"

# May be necessary to run "xhost +" before the following will work
alias proton_chromium="docker run -it --rm \
                                  --cpuset-cpus 0 \
                                  --memory 512mb \
                                  -v /tmp/.X11-unix:/tmp/.X11-unix \
                                  -e DISPLAY=unix$DISPLAY \
                                  -v $HOME/Downloads:/home/chromium/Downloads \
                                  -v $HOME/.config/chromium/:/data \
                                  --security-opt seccomp=$HOME/chrome.json \
                                  --device /dev/snd \
                                  -v /dev/shm:/dev/shm \
                                  --name chromium \
                                  --device /dev/net/tun \
                                  --cap-add=NET_ADMIN \
                                  kyokley/proton_chromium"

setopt NO_NOMATCH

# Source private env vars.
if [ -f "$HOME/.zpriv" ]; then
    source "$HOME/.zpriv"
fi
