#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Disable Prezto safe-ops
zstyle ':prezto:module:utility' safe-ops 'no'

# Editor Settings
export EDITOR='vim'
export SVN_EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

export GOPATH="$HOME/workspace/golang"
export PATH="$HOME/.node_modules_global/bin:$PATH"

#PYENV Setup
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LANGUAGE=en_US.UTF-8

export GPG_TTY=$(tty)

# from /home/yokley/.bashrc
export J2SDKDIR=/usr/lib/jvm/oracle_jdk8
export J2REDIR=/usr/lib/jvm/oracle_jdk8/jre
export PATH=$PATH:/usr/lib/jvm/oracle_jdk8/bin:/usr/lib/jvm/oracle_jdk8/db/bin:/usr/lib/jvm/oracle_jdk8/jre/bin
export JAVA_HOME=/usr/lib/jvm/oracle_jdk8
export DERBY_HOME=/usr/lib/jvm/oracle_jdk8/db

export VT_SHOW_TRACEBACK=true
export VT_DEFAULT_LIST=personal
export VT_PROXY=''
export VT_URL='https://almagest.dyndns.org:7001/vittlify/'

export BROWSER='brave'

export PYENV_VIRTUALENV_DISABLE_PROMPT=1

export PATH=$PATH:~/.cabal/bin
export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:$HOME/.local/bin

export COMPOSE_HTTP_TIMEOUT=180
export DOCKER_BUILDKIT=1
export COMPOSE_DOCKER_CLI_BUILD=1


alias google-chrome='google-chrome --disable-gpu-compositing'
# and/or you can set the django settings module with an environment setting
# export DJANGO_SETTINGS_MODULE='dev_settings'

# Custom git command
alias git-scrub='git branch --merged | grep -v master | xargs git branch -d'

# Alias docker commands
alias krill='docker run --rm -it kyokley/krill'
alias color_git_blame="docker run --rm \
                                  -i \
                                  kyokley/color_blame \
                                  color_git_blame"
alias color_svn_blame="docker run --rm \
                                  -i \
                                  kyokley/color_blame \
                                  color_svn_blame"
alias neomutt="docker run -it --rm --name mutt -e TERM \
                          -v $HOME/.mutt/muttrc:/home/user/.neomuttrc:rw \
                          -v $HOME/.msmtprc:/home/user/.msmtprc:ro \
                          -v /etc/localtime:/etc/localtime:ro \
                          -v $HOME/.mutt/header_cache:/home/user/.mutt/header_cache:rw \
                          -v $HOME/.mutt/body_cache:/home/user/.mutt/body_cache \
                          -v $HOME/.mutt/password:/home/user/.mutt/password \
                          kyokley/neomutt"

# May be necessary to run "xhost +" before the following will work
alias proton_chromium="xhost + && docker run -it --rm \
                                  --cpuset-cpus 0 \
                                  --memory 512mb \
                                  -v /tmp/.X11-unix:/tmp/.X11-unix \
                                  -e DISPLAY=unix$DISPLAY \
                                  -v $HOME/Downloads:/home/chromium/Downloads \
                                  -v $HOME/.config/chromium/:/data \
                                  --security-opt seccomp=$HOME/chrome_sec.json \
                                  --device /dev/snd \
                                  -v /dev/shm:/dev/shm \
                                  --name chromium \
                                  --device /dev/net/tun \
                                  --cap-add=NET_ADMIN \
                                  kyokley/proton_chromium"

alias sqlparse="docker run --rm \
                           -i \
                           kyokley/sqlparse"

alias vimdiff='vim -d'

function docker-vivaldi(){
    xhost + >/dev/null
    docker run --rm -it -d \
        --memory 4gb \
        --shm-size=2g \
        -v /etc/localtime:/etc/localtime:ro \
        -v /tmp/.X11-unix:/tmp/.X11-unix \
        -e DISPLAY=unix$DISPLAY \
        --security-opt seccomp:${HOME}/chrome_sec.json \
        --privileged \
        --device /dev/snd \
        -v /dev/shm:/dev/shm \
        --device /dev/net/tun \
        --cap-add=NET_ADMIN \
        -v ${HOME}/.cache/vivaldi:/home/vivaldi/.cache/vivaldi \
        -v ${HOME}/.config/vivaldi:/home/vivaldi/.config/vivaldi \
        -v ${HOME}/.vivaldi/pki:/home/vivaldi/.pki \
        -v ${HOME}/Downloads:/home/vivaldi/Downloads \
        --name vivaldi \
        kyokley/vivaldi "$@"
}

git-absolute-path () {
    fullpath=$([[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}")
    if [ $(git rev-parse --show-superproject-working-tree) ]
    then
        gitroot="$(git rev-parse --show-superproject-working-tree)"
    else
        gitroot="$(git rev-parse --show-toplevel)" || return 1
    fi
    [[ "$fullpath" =~ "$gitroot" ]] && echo "${fullpath/$gitroot\//}"
}

function dvim() {
    xhost + >/dev/null
    ROOT_HOME="/root"

    GIT_ROOT=$(git rev-parse --show-toplevel 2>/dev/null)

    if [ $? -eq 0 ]
    then
        TITLE_ROOT="$GIT_ROOT"

        if [ $(git rev-parse --show-superproject-working-tree 2>/dev/null) ]
        then
            GIT_ROOT="$(git rev-parse --show-superproject-working-tree)"
        fi

        docker run \
            --rm -it \
            -e DISPLAY=unix$DISPLAY \
            -v /tmp/.X11-unix:/tmp/.X11-unix \
            -v "$GIT_ROOT":/files \
            -v "$HOME"/.vimbackup:"$ROOT_HOME"/.vimbackup \
            -v "$HOME"/.vimswap:"$ROOT_HOME"/.vimswap \
            -v "$HOME"/.vimundodir:"$ROOT_HOME"/.vimundodir \
            -v "$HOME"/.vimviews:"$ROOT_HOME"/.vimviews \
            -v "$HOME"/.local/share/nvim/shada:"$ROOT_HOME"/.shada \
            kyokley/neovim-custom \
            -i "$ROOT_HOME"/.shada/dvim_main.shada \
            --cmd "let g:git_root = \"${TITLE_ROOT}\"" \
            $(
                    for file in $@
                    do
                        echo $(git-absolute-path "$file")
                    done
                )
    else
        docker run \
            --rm -it \
            -e DISPLAY=unix$DISPLAY \
            -v /tmp/.X11-unix:/tmp/.X11-unix \
            -v $(pwd):/files \
            kyokley/neovim-custom \
            "$@"
    fi
}

function init-psql() {
    touch $HOME/.psql_history

    mkdir -p $HOME/.config/pgcli
    touch $HOME/.config/pgcli/history
    touch $HOME/.pgpass
}

function psql() {
    docker run \
        --rm -it \
        --net=host \
        -e "PGTZ=America/Chicago" \
        -e "PSQL_HISTORY=/root/.psql_history" \
        -v "$HOME/.psql_history:/root/.psql_history" \
        -v "/tmp:/tmp" \
        -v "$(pwd):/workspace" \
        -v "$HOME/.pgpass:/root/.pgpass" \
        kyokley/psql \
        "$@"
}

function pgcli() {
    docker run \
        --rm -it \
        --net=host \
        -e UID="$(id | grep -Po '(?<=uid=)\d+')" \
        -e GID="$(id | grep -Po '(?<=gid=)\d+')" \
        -e "PGTZ=America/Chicago" \
        -v "$HOME/.config/pgcli/history:/root/.config/pgcli/history" \
        -v "/tmp:/tmp" \
        -v "$(pwd):/workspace" \
        -v "$HOME/.pgpass:/root/.pgpass" \
        kyokley/pgcli \
        "$@"
}

function pg_dump() {
    docker run \
        --rm -it \
        --net=host \
        -e "PGTZ=America/Chicago" \
        -v "$HOME/.pgpass:/root/.pgpass" \
        --entrypoint "pg_dump" \
        kyokley/psql \
        "$@"
}

# This function is specially designed to accept a db dump on stdin
# and load it into a database
function pg_load(){
    docker run \
        --rm -i \
        --net=host \
        -v "$HOME/.pgpass:/root/.pgpass" \
        kyokley/psql \
        "$@"
}


function createdb() {
    docker run \
        --rm -it \
        --net=host \
        -e "PGTZ=America/Chicago" \
        -v "$HOME/.pgpass:/root/.pgpass" \
        --entrypoint "createdb" \
        kyokley/psql \
        "$@"
}

function dropdb() {
    docker run \
        --rm -it \
        --net=host \
        -e "PGTZ=America/Chicago" \
        -v "$HOME/.pgpass:/root/.pgpass" \
        --entrypoint "dropdb" \
        kyokley/psql \
        "$@"
}

function diffr() {
    docker run --rm -i kyokley/diffr "$@" | less -R
}

function diff-so-fancy() {
    docker run --rm -i kyokley/diff-so-fancy "$@" 2>/dev/null | less -R
}
alias dsf='diff-so-fancy'

function delta() {
    docker run --rm -i kyokley/delta "$@" 2>/dev/null | less -R
}

function lockbox() {
    UID="$(id | grep -Po '(?<=uid=)\d+')"
    GID="$(id | grep -Po '(?<=gid=)\d+')"
    docker run \
           --rm -it \
           -u $UID:$GID \
           -v $(pwd):/files \
           kyokley/lockbox "$@"
}

function qw() {
    UID="$(id | grep -Po '(?<=uid=)\d+')"
    GID="$(id | grep -Po '(?<=gid=)\d+')"
    docker run \
           --rm -it \
           -u $UID:$GID \
           kyokley/quick-word "$@"
}

# Some commands to open github pages
function gh-url(){
    # Borrowed bits of the following from:
    # https://github.com/oguzbilgic/dotfiles/blob/master/config/fish/functions/gh.fish

    origin=$(git remote get-url origin)
    repo=$(echo $origin | python -c "import sys; url = sys.stdin.readline().strip(); print(url.split(':')[1][:-4])")
    echo "https://github.com/$repo"
}
function gh(){
    xdg-open $(gh-url) 2>&1 > /dev/null &
}
function gh-pr(){
    xdg-open "$(gh-url)/pulls" 2>&1 > /dev/null &
}

function lazydocker(){
    mkdir -p $HOME/.config/lazydocker
    docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock \
                        -v ~/.config/lazydocker:/.config/jesseduffield/lazydocker \
                        lazyteam/lazydocker
}

function calories(){
    docker run --rm -it -v /home/yokley/.config/calories/calories.db:/root/calories.db -v /home/yokley/.config/calories/caloriesconf:/go/bin/.caloriesconf kyokley/calories "$@"
}

function chpwd(){
    export GIT_BASE='master'
    if [ -r $PWD/.zsh_config ]; then
        source $PWD/.zsh_config
    fi
}

function open(){
    for arg in $@
    do
        xdg-open $arg &
    done
}

function strip(){
    mv "$1" $(echo "$1" | sed 's/ /_/g')
}

function vt(){
    docker run --rm \
        -t \
        -v ~/.ssh:/root/.ssh \
        --env VT_URL=$VT_URL \
        --env VT_USERNAME=yokley \
        --env VT_DEFAULT_LIST=$VT_DEFAULT_LIST \
        --env VT_PROXY=$VT_PROXY \
        --net=host \
        kyokley/vt $@
    }

function open-vimswap(){
    for file in ~/.vimswap/*
    do
        basename "$file" | sed 's!%!/!g' | sed -E 's!\.s[a-z]{2}$!!'
    done | xargs vim
}

function jirabot(){
    docker run --rm -it -e JIRA_DOMAIN="$JIRA_DOMAIN" -v $HOME/.config/jirabot/creds:/root/.config/jirabot/creds kyokley/jirabot $@
}
function jira(){
    if [ -z "$1" ]
    then
        issue=$(jirabot issue --quiet | sed 's/\s\+$//' | grep -vE '^$' | rofi -dmenu -i -multi-select -p "jira" | awk '{print $1}')
        if [ $? -eq 0 ] && [ ! -z "$issue" ]
        then
            jirabot issue $issue
        fi
    else
        jirabot issue $@
    fi
}

function mv-cli(){
    docker run --rm -it \
        -v /tmp/.X11-unix:/tmp/.X11-unix \
        -e DISPLAY=$DISPLAY \
        -e MV_CLI_SERVER_URI=$MV_CLI_SERVER_URI \
        --device /dev/snd \
        --device /dev/dri/card0 \
        -v /dev/shm:/dev/shm \
        -v /dev/dri/card0:/dev/dri/card0 \
        -v $HOME/.config/mv_creds:/root/.mv_creds \
        kyokley/mv-cli $@
}

function tv-cli(){
    if [ -z "$1" ]
    then
        PATH_ID=$(tv-cli tv | rofi -dmenu -i -pid /tmp/rofi.2 | grep -Po '(?<=\(id=)\d+')
        if [ $? -eq 0 ]
        then
            TV_ID=$(tv-cli tv --path $PATH_ID | rofi -dmenu -i -pid /tmp/rofi.1 | grep -Po '(?<=\(id=)\d+')
            if [ $? -eq 0 ]
            then
                tv-cli tv $TV_ID
            fi
        fi
    else
        mv-cli $@
    fi
}

function movie-cli(){
    if [ -z "$1" ]
    then
        MOVIE_ID=$(movie-cli movie | rofi -dmenu -i -pid /tmp/rofi.2 | grep -Po '(?<=\(id=)\d+')
        if [ $? -eq 0 ]
        then
            movie-cli movie $MOVIE_ID
        fi
    else
        mv-cli $@
    fi
}

alias asciicast2gif='docker run --rm -v $PWD:/data asciinema/asciicast2gif'

setopt NO_NOMATCH
xhost + 2>&1 >/dev/null

# Source private env vars.
if [ -f "$HOME/.zpriv" ]; then
    source "$HOME/.zpriv"
fi
