#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
fpath=(~/dotfiles/prezto/modules/wd $fpath)

wd() {
    . ~/dotfiles/prezto/modules/wd/wd.sh
}

compinit -i

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# autoload -Uz compinit
# compinit
# Completion for kitty
which kitty >/dev/null 2>&1 && kitty + complete setup zsh | source /dev/stdin

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/yokley/google-cloud-sdk/path.zsh.inc' ]; then . '/home/yokley/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/yokley/google-cloud-sdk/completion.zsh.inc' ]; then . '/home/yokley/google-cloud-sdk/completion.zsh.inc'; fi
