#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
fpath=(~/dotfiles/prezto/modules/wd $fpath)

wd() {
    . ~/dotfiles/prezto/modules/wd/wd.sh
}

compinit -i

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# autoload -Uz compinit
# compinit
# Completion for kitty
which kitty >/dev/null 2>&1 && kitty + complete setup zsh | source /dev/stdin

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/yokley/google-cloud-sdk/path.zsh.inc' ]; then . '/home/yokley/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/yokley/google-cloud-sdk/completion.zsh.inc' ]; then . '/home/yokley/google-cloud-sdk/completion.zsh.inc'; fi

SPACESHIP_TIME_SHOW=true
SPACESHIP_DIR_TRUNC=3
SPACESHIP_EXIT_CODE_SHOW=true
SPACESHIP_EXIT_CODE_SYMBOL=''
SPACESHIP_EXIT_CODE_PREFIX=''
SPACESHIP_EXIT_CODE_SUFFIX=' '
SPACESHIP_PROMPT_ORDER=(
    user          # Username section
    dir           # Current directory section
    host          # Hostname section
    git           # Git section (git_branch + git_status)
    hg            # Mercurial section (hg_branch  + hg_status)
    package       # Package version
    node          # Node.js section
    ruby          # Ruby section
    elixir        # Elixir section
    swift         # Swift section
    golang        # Go section
    php           # PHP section
    rust          # Rust section
    haskell       # Haskell Stack section
    julia         # Julia section
    # docker        # Docker section
    aws           # Amazon Web Services section
    venv          # virtualenv section
    conda         # conda virtualenv section
    pyenv         # Pyenv section
    dotnet        # .NET section
    ember         # Ember.js section
    kubecontext   # Kubectl context section
    terraform     # Terraform workspace section
    exec_time     # Execution time
    line_sep      # Line break
    battery       # Battery level and status
    vi_mode       # Vi-mode indicator
    jobs          # Background jobs indicator
    char          # Prompt character
)
SPACESHIP_RPROMPT_ORDER=(
    exit_code     # Exit code section
    time
)

### Added by Zplugin's installer
# source "$HOME/.zplugin/bin/zplugin.zsh"
# autoload -Uz _zplugin
# (( ${+_comps} )) && _comps[zplugin]=_zplugin
### End of Zplugin installer's chunk
